#ifndef DOCUMENTVIEWERGLOBAL_H
#define DOCUMENTVIEWERGLOBAL_H

#include <QtCore/QtGlobal>

#if defined(DOCUMENTVIEWER_LIBRARY)
#  define DOCUMENTVIEWER_EXPORT Q_DECL_EXPORT
#else
#  define DOCUMENTVIEWER_EXPORT Q_DECL_IMPORT
#endif

#endif // DOCUMENTVIEWERGLOBAL_H

