/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OfficeServiceIfAdaptor -a officetoolsserviceifadaptor.h:officetoolsserviceidadaptor.cpp com.nokia.maemo.meegotouch.OfficeToolsInterface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef OFFICETOOLSSERVICEIFADAPTOR_H_1320403783
#define OFFICETOOLSSERVICEIFADAPTOR_H_1320403783

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.nokia.maemo.meegotouch.OfficeToolsInterface
 */
class OfficeServiceIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.nokia.maemo.meegotouch.OfficeToolsInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.nokia.maemo.meegotouch.OfficeToolsInterface\">\n"
"    <doc>\n"
"      <arg tag=\"brief\">\n"
"                Interface for opening office files.\n"
"            </arg>\n"
"      <arg tag=\"details\">\n"
"                Interface for opening office files..\n"
"            </arg>\n"
"    </doc>\n"
"    <method name=\"OpenFile\">\n"
"      <!--doc>\n"
"                <arg tag=\"brief\">\n"
"                    Method called to launch office document viewer for viewing\n"
"                    selected file.\n"
"                </arg>\n"
"                <arg tag=\"details\">\n"
"                    The document application accepts PDF and most MS formats\n"
"                    as files which it can render.\n"
"\n"
"                    In the future more filetypes may be supported.\n"
"\n"
"                    If the opened filetype is not supported, error message is\n"
"                    is shown.\n"
"                </arg>\n"
"            </doc-->\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"\"/>\n"
"    </method>\n"
"    <method name=\"launchFile\">\n"
"      <!--doc>\n"
"                <arg tag=\"brief\">\n"
"                    Method called to launch office document viewer for viewing\n"
"                    selected file.              \n"
"                </arg>\n"
"                <arg tag=\"details\">\n"
"                    The document application accepts PDF and most MS formats\n"
"                    as files which it can render.\n"
"\n"
"                    In the future more filetypes may be supported.\n"
"\n"
"                    If the opened filetype is not supported, error message is      \n"
"                    is shown.\n"
"                </arg>\n"
"            </doc-->\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"\"/>\n"
"    </method>\n"
"    <signal name=\"showFrontPage\"/>\n"
"    <signal name=\"lookForPopup\"/>\n"
"    <signal name=\"closeFile\"/>\n"
"  </interface>\n"
        "")
public:
    OfficeServiceIfAdaptor(QObject *parent);
    virtual ~OfficeServiceIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool OpenFile(const QString &filename);
    bool launchFile(const QString &filename);
Q_SIGNALS: // SIGNALS
    void closeFile();
    void lookForPopup();
    void showFrontPage();
};

#endif
