/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OfficeServiceIfAdaptor -a officetoolsserviceifadaptor.h:officetoolsserviceidadaptor.cpp com.nokia.maemo.meegotouch.OfficeToolsInterface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "officetoolsserviceifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class OfficeServiceIfAdaptor
 */

OfficeServiceIfAdaptor::OfficeServiceIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

OfficeServiceIfAdaptor::~OfficeServiceIfAdaptor()
{
    // destructor
}

bool OfficeServiceIfAdaptor::OpenFile(const QString &filename)
{
    // handle method call com.nokia.maemo.meegotouch.OfficeToolsInterface.OpenFile
    bool out0;
    QMetaObject::invokeMethod(parent(), "OpenFile", Q_RETURN_ARG(bool, out0), Q_ARG(QString, filename));
    return out0;
}

bool OfficeServiceIfAdaptor::launchFile(const QString &filename)
{
    // handle method call com.nokia.maemo.meegotouch.OfficeToolsInterface.launchFile
    bool out0;
    QMetaObject::invokeMethod(parent(), "launchFile", Q_RETURN_ARG(bool, out0), Q_ARG(QString, filename));
    return out0;
}

